### ISSUE TITLE
Christian God Buff

### ISSUE THREAD

**Issue by Idk1313** [malonnnn/ServerConfig2#106]
From Genesis 19 verse 24-26.  24 Then the Lord rained down burning sulfur on Sodom and Gomorrah—from the Lord out of the heavens. 25 Thus he overthrew those cities and the entire plain, destroying all those living in the cities—and also the vegetation in the land. 26 But Lot’s wife looked back, and she became a pillar of salt.
For this I believe that God should be given /destroyworld and /explode to destroy people easily.

**Comment by malonnnn** [comment]
he has been given a meteor shower wand, which lets him rain down fire from the heavens :D

Thanks for the suggestion!
