### ISSUE TITLE
JOKER

### ISSUE THREAD

**Issue by superiorxman** [malonnnn/ServerConfig2#113]
I would like Joker to have Laughing Gas, Joy Buzzer, Acid Flower, and a Bazooka!

**Comment by malonnnn** [comment]
This requires proofs, like a picture of joker with a bazooka or a video of joker with his laughing gas

**Comment by superiorxman** [comment]
http://vlnresearch.com/wp-content/uploads/2016/04/Joker-Batman-Animated-Series-flower.png
Acid Flower

**Comment by superiorxman** [comment]
http://vignette2.wikia.nocookie.net/batman/images/d/d1/Joker%27s_Joy_Buzzer_%28comics%29.png/revision/latest/scale-to-width-down/250?cb=20161206000146
Joy Buzzer

**Comment by superiorxman** [comment]
http://www.batmanwallpapers.com/wp-content/uploads/wallpapers/joker_fires_bazooka_wallpaper_-_1024x768.jpg
Bazooka

**Comment by superiorxman** [comment]
http://vignette3.wikia.nocookie.net/batman/images/2/21/JokerVenomVictim.jpg/revision/latest?cb=20170222124647
Joker Venom

**Comment by malonnnn** [comment]
Joker Flower Acid
/mgive <plr> jokerfloweracidwand

Joker Venom
powers.jokervenom
/jokervenom

Bazooka
/give <plr> rocketlauncher

Joy Buzzer
powers.joybuzzer
/joybuzzer <player>
