### ISSUE TITLE
Panda power for Meilin

### ISSUE THREAD

**Issue by Chief-Sly-Fox** [malonnnn/ServerConfig2#137]
Make a power similar to Thawne Time Remnants called /producejhi that spawns in one dog disguised as a polar bear with the name "Jhi"  and another power /returnjhi that despawns it.  @malonnnn .

**Comment by Chief-Sly-Fox** [comment]
*Proof*
https://cdn.discordapp.com/attachments/411022508687491072/427933420468043810/20180326_134217.jpg

**Comment by malonnnn** [comment]
timmy told me to close meilin... so...  :\
