### ISSUE TITLE
Jhi for Meilin

### ISSUE THREAD

**Issue by Chief-Sly-Fox** [malonnnn/ServerConfig2#139]
Make a power similar to Thawne Time Remnants called /producejhi that spawns in one dog disguised as a polar bear with the name "Jhi" and another power /returnjhi that despawns it. @malonnnn .

Proof:

Jhi
https://cdn.discordapp.com/attachments/411022508687491072/427933420468043810/20180326_134217.jpg

Return
https://cdn.discordapp.com/attachments/411022508687491072/427933419914133504/20180326_134642.jpg

Produce
https://cdn.discordapp.com/attachments/411022508687491072/427933420468043806/20180326_134749.jpg

**Comment by malonnnn** [comment]
the command is /jhi

summons and returns
