### ISSUE TITLE
Jokervenom v2

### ISSUE THREAD

**Issue by Chief-Sly-Fox** [malonnnn/ServerConfig2#155]
Make a command that gives joker (like 3) splash potions named "Joker Venom" (Make them neon green or something) And have them have the Nausea 2 effect (Or whatever potion effect you think is best) And make it so when a player has the nausea 2 level on them they start the joker venom laughing sequence. You can use this to make the potion: http://minecraft.tools/en/potion.php

**Comment by malonnnn** [comment]
give joker the command

/potion jokervenom
