### ISSUE TITLE
Poseidon 

### ISSUE THREAD

**Issue by Deadshot361** [malonnnn/ServerConfig2#94]
I think it'd be cool if Poseidon had a /flood ability where  it actually has a real huge wave of water that surges and pushes people back and after like 10 seconds or so or something the water dissapears.  Something like that I've seen all of his moves are just particle and not actually water which I think water would be more fun

**Comment by malonnnn** [comment]
This is now finished.

Permission:
powers.drown

Usage:
/drown <player>
